version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: fastrag
      POSTGRES_USER: fastrag
      POSTGRES_PASSWORD: fastrag
      POSTGRES_SHARED_BUFFERS: 2GB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 6GB
      POSTGRES_MAINTENANCE_WORK_MEM: 512MB
      POSTGRES_RANDOM_PAGE_COST: 1.1
      POSTGRES_EFFECTIVE_IO_CONCURRENCY: 200
      POSTGRES_WORK_MEM: 16MB
      POSTGRES_MIN_WAL_SIZE: 2GB
      POSTGRES_MAX_WAL_SIZE: 8GB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "fastrag", "-d", "fastrag"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

volumes:
  postgres_data: 